Nama: Muhammad Yasir Anshari Haq

NIM: 226150100111009

Kelas: Sistem Cerdas - B

Tugas: LVQ

In [36]:
import numpy as np  
import pandas as pd
import sympy as sp
from sympy import Pow
import openpyxl
import math

In [37]:
data = openpyxl.load_workbook(r'D:\Tugas UB\S2\Semester 1\Sistem Cerdas\Tugas\Tugas 4\LVQ\dataset.xlsx')
sheet = data.active
bobot = np.zeros((2,7))
for i in range(2):
    n=i+1
    bobot[i][0]=sheet['K'+str(n)].value
    bobot[i][1]=sheet['L'+str(n)].value
    bobot[i][2]=sheet['M'+str(n)].value
    bobot[i][3]=sheet['N'+str(n)].value
    bobot[i][4]=sheet['O'+str(n)].value
    bobot[i][5]=sheet['P'+str(n)].value
    bobot[i][6]=sheet['R'+str(n)].value
print("Ambil Bobot Awal dari excel:\n", bobot)

Ambil Bobot Awal dari excel:
 [[1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 2.]]


In [38]:
x = np.zeros((8,7))
for i in range(8):
    n=i+1
    x[i][0]=sheet['A'+str(n)].value
    x[i][1]=sheet['B'+str(n)].value
    x[i][2]=sheet['C'+str(n)].value
    x[i][3]=sheet['D'+str(n)].value
    x[i][4]=sheet['E'+str(n)].value
    x[i][5]=sheet['F'+str(n)].value
    x[i][6]=sheet['H'+str(n)].value
print("Ambil nilai x dari excel:\n", x)


Ambil nilai x dari excel:
 [[0. 0. 1. 0. 0. 1. 1.]
 [0. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 0. 0. 1. 1.]
 [1. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 1. 0. 0. 2.]
 [0. 1. 0. 1. 0. 0. 2.]
 [1. 0. 0. 1. 0. 1. 2.]
 [0. 1. 1. 1. 1. 1. 2.]]


In [39]:
w = np.zeros((2,7))
for i in range(2):
    for j in range(7):
        w[i][j]=bobot[i][j]
print('Bobot Awal:\n', w)

Bobot Awal:
 [[1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 2.]]


In [46]:
max_epoch = 10
euc_dist_w1 = 0
euc_dist_w2 = 0
target = 0
learning_rate = .05
for _ in range(max_epoch):
    print("Epoch-", (_+1), "\nLearning Rate: ", learning_rate)
    for i in range(len(x)):
        euc_dist_w1 = sp.sqrt(Pow((x[i][0] - w[0][0]), 2)+Pow((x[i][1] - w[0][1]), 2)+Pow((x[i][2] - w[0][2]), 2)+Pow(
            (x[i][3] - w[0][3]), 2)+Pow((x[i][4] - w[0][4]), 2)+Pow((x[i][5] - w[0][5]), 2))
        euc_dist_w2 = sp.sqrt(Pow((x[i][0] - w[1][0]), 2)+Pow((x[i][1] - w[1][1]), 2)+Pow((x[i][2] - w[1][2]), 2)+Pow(
            (x[i][3] - w[1][3]), 2)+Pow((x[i][4] - w[1][4]), 2)+Pow((x[i][5] - w[1][5]), 2))

        if euc_dist_w1 <= euc_dist_w2:
            for j in range(6):
                if x[i][6] == w[0][6]:
                    w[0][j-1] = w[0][j-1] + \
                        (learning_rate*(x[0][j-1]-w[0][j-1]))
                else:
                    w[0][j-1] = w[0][j-1] - \
                        (learning_rate*(x[0][j-1]-w[0][j-1]))
        else:
            for j in range(6):
                if x[i][6] == w[0][6]:
                    w[1][j-1] = w[1][j-1] + \
                        (learning_rate*(x[0][j-1]-w[1][j-1]))
            else:
                w[1][j-1] = w[1][j-1] - (learning_rate*(x[0][j-1]-w[1][j-1]))
        print("-----------------")
        print('Data Ke-', (i+1))
        print("-----------------")
        print('jarak bobot 1 = ', euc_dist_w1, ' jarak bobot 2', euc_dist_w2)
        result = 1 if euc_dist_w1 <= euc_dist_w2 else 2
        print('result= ', result, ' target = ', round(x[i][6]))
        if euc_dist_w1 <= euc_dist_w2:
            print('w1 = ', w[0])
        else:
            print('w2 = ', w[1])

    learning_rate = learning_rate - (learning_rate * .1)

print('Hasil\n', 'w1=', w[0], '\nw2=', w[1])


Epoch- 1 
Learning Rate:  0.05
-----------------
Data Ke- 1
-----------------
jarak bobot 1 =  1.13161008268787  jarak bobot 2 3.21857008526715
result=  1  target =  1
w1 =  [0.29051024 0.         0.70948976 0.         0.29051024 0.
 1.        ]
-----------------
Data Ke- 2
-----------------
jarak bobot 1 =  0.819858597079394  jarak bobot 2 2.22117688048958
result=  1  target =  1
w1 =  [0.27598473 0.         0.72401527 0.         0.27598473 0.
 1.        ]
-----------------
Data Ke- 3
-----------------
jarak bobot 1 =  1.63601138596081  jarak bobot 2 3.21857008526715
result=  1  target =  1
w1 =  [0.26218549 0.         0.73781451 0.         0.26218549 0.
 1.        ]
-----------------
Data Ke- 4
-----------------
jarak bobot 1 =  1.46883686448806  jarak bobot 2 2.63317806735918
result=  1  target =  1
w1 =  [0.24907622 0.         0.75092378 0.         0.24907622 0.
 1.        ]
-----------------
Data Ke- 5
-----------------
jarak bobot 1 =  1.08908993329770  jarak bobot 2 2.8912269702